Repository OrcaBus/service-shared-resources, pull requests merged in 2025-06, with the labels that each got.

#2 Feat: Migrate Shared Stack
  bin/deploy.ts
  cdk.context.json
  infrastructure/stage/config.ts
  infrastructure/stage/constructs/compute/index.ts
  infrastructure/stage/constructs/database/index.ts
  infrastructure/stage/constructs/event-bus/custom-event-archiver/Makefile
  infrastructure/stage/constructs/event-bus/custom-event-archiver/README.md
  infrastructure/stage/constructs/event-bus/custom-event-archiver/archive_service/__init__.py
  infrastructure/stage/constructs/event-bus/custom-event-archiver/archive_service/tests/test_universal_event_archiver.py
  infrastructure/stage/constructs/event-bus/custom-event-archiver/archive_service/universal_event_archiver.py
  infrastructure/stage/constructs/event-bus/custom-event-archiver/construct/universal-event-archiver/index.ts
  infrastructure/stage/constructs/event-bus/custom-event-archiver/deps/requirements-test.txt
  infrastructure/stage/constructs/event-bus/index.ts
  infrastructure/stage/constructs/event-dlq/index.ts
  infrastructure/stage/constructs/event-source/index.ts
  infrastructure/stage/constructs/schema-registry/index.ts
  infrastructure/stage/deployment-stack.ts
  infrastructure/stage/stack.ts
  infrastructure/toolchain/stateful-stack.ts
  package.json
  pnpm-lock.yaml
  test/stage.test.ts
Labels: enhancement

#8 refactor: remove event source and dlq
  infrastructure/shared-stack/stage/config.ts
  infrastructure/shared-stack/stage/constructs/event-dlq/index.ts
  infrastructure/shared-stack/stage/constructs/event-source/index.ts
  infrastructure/shared-stack/stage/stack.ts
  test/shared-stack.test.ts
Labels: refactor

#9 Fixed Token Service stack setup
  .prettierignore
  Makefile
  infrastructure/token-service/stage/Makefile
  infrastructure/token-service/stage/README.md
  infrastructure/token-service/stage/deploy/config.ts
  infrastructure/token-service/stage/deploy/policy.ts
  infrastructure/token-service/stage/deploy/stack.ts
  infrastructure/token-service/toolchain/pipeline.ts
  test/token-service.test.ts
Labels: documentation, refactor
